package id.infinitelearning.KotlinSubmission.exercise4

import java.lang.NumberFormatException

fun main() {
    var x = 1
    var y = 25
    try {
        val  hasil = x / y
        println(hasil)
    }catch (e: NumberFormatException){
        println("error")
    }
}
/**
 * Buatlah contoh code penggunaan try catch untuk menangani suatu kasus sesuai keinginan teman-teman
 *
 */
// Buat di bawah sini
